name: base-image-build

on:
  workflow_dispatch:
  push:

env:
  DOCKER_HUB_NAMESPACE: whicha
  DOCKER_HUB_REPOSITORY: ubuntu2204

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out to target branch
        uses: actions/checkout@v4
        with:
          ref: ${{github.ref_name}}

      - name: Get current time
        id: build_time
        run: |
          echo "build_time=$(date +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT

      - name: Define some variables
        id: variables
        run: |
          echo "time_tag=${{ env.DOCKER_HUB_NAMESPACE }}/${{ env.DOCKER_HUB_REPOSITORY }}:${{github.ref_name}}-${{ steps.build_time.outputs.build_time }}" >> $GITHUB_OUTPUT
          echo "latest_tag=${{ env.DOCKER_HUB_NAMESPACE }}/${{ env.DOCKER_HUB_REPOSITORY }}:${{github.ref_name}}-latest" >> $GITHUB_OUTPUT
          echo "tarball_name=${{ env.DOCKER_HUB_REPOSITORY }}-${{github.ref_name}}-${{ steps.build_time.outputs.build_time }}.tar" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./context
          file: ./Dockerfile
          push: true
          tags: |
            ${{ steps.variables.outputs.time_tag }}
            ${{ steps.variables.outputs.latest_tag }}
            

      - name: Pull, pack and compress image files
        run: |
          docker pull ${{ steps.variables.outputs.time_tag }}
          docker save -o ${{ steps.variables.outputs.tarball_name }} ${{ steps.variables.outputs.time_tag }}
          tar -czf ${{ steps.variables.outputs.tarball_name }}.gz ${{ steps.variables.outputs.tarball_name }}
          docker rmi ${{ steps.variables.outputs.time_tag }}
          rm ${{ steps.variables.outputs.tarball_name }}

      - name: Release the latest image
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ steps.variables.outputs.time_tag }}
          files: |
            ${{ steps.variables.outputs.tarball_name }}.gz
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
